version: "3.3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: habrpguser
      POSTGRES_PASSWORD: pgpwd4habr
    ports:
      - "5432:5432"